insert into STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE)values(101,'HCL',1557.85);
insert into STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE)values(102,'INFOSYS',1508.85);
insert into STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE)values(103,'TECHMAHINDRA',1262.65);
insert into STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE)values(104,'TCS',3910.90);
insert into STOCK_PRICE(STOCK_ID,COMPANY_NAME,COMPANY_PRICE)values(105,'WIPRO',487.10);